# Generated by Django 4.2.3 on 2023-09-14 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=125)),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('experience_level', multiselectfield.db.fields.MultiSelectField(choices=[('Internship', 'Internship'), ('Entry Level', 'Entry Level'), ('Associate', 'Associate'), ('Mid-Senior Level', 'Mid-Senior Level'), ('Senior Level', 'Senior Level'), ('Director', 'Director'), ('Executive', 'Executive')], max_length=125)),
                ('job_poster', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
