# Generated by Django 4.2.3 on 2023-09-10 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=125)),
                ('experience_level', models.CharField(choices=[('Internship', 'Internship'), ('Entry Level', 'Entry Level'), ('Associate', 'Associate'), ('Mid-Senior Level', 'Mid-Senior Level'), ('Senior Level', 'Senior Level'), ('Director', 'Director'), ('Exercutive', 'Exercutive')], max_length=100)),
            ],
        ),
    ]
