# Generated by Django 4.2.3 on 2023-09-11 00:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='date_posted',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='job_poster',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='experience_level',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Internship', 'Internship'), ('Entry Level', 'Entry Level'), ('Associate', 'Associate'), ('Mid-Senior Level', 'Mid-Senior Level'), ('Senior Level', 'Senior Level'), ('Director', 'Director'), ('Exercutive', 'Exercutive')], max_length=125),
        ),
    ]
