# Generated by Django 4.2.3 on 2023-09-14 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='skills',
        ),
    ]
