# Generated by Django 4.2.3 on 2023-09-11 00:24

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_alter_job_job_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='experience_level',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Internship', 'Internship'), ('Entry Level', 'Entry Level'), ('Associate', 'Associate'), ('Mid-Senior Level', 'Mid-Senior Level'), ('Senior Level', 'Senior Level'), ('Director', 'Director'), ('Executive', 'Executive')], max_length=125),
        ),
    ]
