# Generated by Django 4.2.3 on 2023-09-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_remove_job_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
