# Generated by Django 4.2.3 on 2023-09-11 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_alter_job_experience_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date_posted',
            field=models.DateField(),
        ),
    ]
