# Generated by Django 4.2.3 on 2023-09-15 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_remove_job_skills_job_job_details_job_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_details',
            field=models.TextField(null=True),
        ),
    ]
