# Generated by Django 4.2.3 on 2023-09-15 21:22

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_alter_job_job_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='date_posted',
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Remote', 'Remote'), ('On-site', 'On-site'), ('Hybrid', 'Hybrid')], max_length=125),
        ),
    ]
