# Generated by Django 4.2.3 on 2023-09-15 21:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_remove_job_date_posted_alter_job_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='date_posted',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
