# Generated by Django 4.2.3 on 2023-09-16 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_job_date_posted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='date_posted',
        ),
    ]
