# Generated by Django 4.2.3 on 2023-09-16 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_job_company_name_job_conpany_website_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='conpany_website_link',
            new_name='company_website_link',
        ),
    ]
