# Generated by Django 4.2.3 on 2023-09-17 00:53

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_rename_conpany_website_link_job_company_website_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_alternative_location',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='job_location',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
