# Generated by Django 4.2.3 on 2023-09-17 01:05

from django.db import migrations, models
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_job_job_alternative_location_job_job_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_salary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_location',
            field=django_countries.fields.CountryField(blank=True, default=django.utils.timezone.now, max_length=746, multiple=True),
            preserve_default=False,
        ),
    ]
