# Generated by Django 4.2.3 on 2023-09-17 01:38

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0015_job_job_salary_alter_job_job_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_details',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
